baseURL = "https://data-apis.org/"
languageCode = "en-us"
title = "Consortium for Python Data API Standards"
theme = "kube"
description = "The purpose of the Consortium is to develop API standards for common Python data structures for scientific, data science and machine learning users and applications - using a combination of design discussions, requirements engineering and data-driven approaches."
Paginate = 4
pygmentsUseClasses = true
relativeURLs = true

[Params]
  RSSLink = "/index.xml"
  author = "Consortium for Python Data API Standards"
  github = "data-apis"
#  twitter = ""
#  email = ""

#[[menu.main]]
#    name = "Docs"
#    weight = -100
#    url = "/docs/"

[[menu.main]]
    name = "Blog"
    weight = -60
    url = "/blog/"

[[menu.main]]
    name = "Array API"
    weight = -100
    url = "https://data-apis.org/array-api/latest/"

[[menu.main]]
    name = "DataFrame API"
    weight = -90
    url = "https://data-apis.org/dataframe-api/draft/"

[[menu.main]]
    name = "DataFrame interchange protocol"
    weight = -80
    url = "https://data-apis.org/dataframe-protocol/latest/"

[[menu.main]]
    name = "Annual reports"
    weight = -50
    url = "/annual-reports/"

# To render raw html tags within Markdown
[markup.goldmark.renderer]
unsafe= true
